#
# Copyright Altoros. All Rights Reserved.
#

version: '2'

services:

  ca.courier2.blockchain.localhost:
    container_name: ca.courier2.blockchain.localhost
    image: hyperledger/fabric-ca:x86_64-1.0.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.courier2.blockchain.localhost-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6e3490b505fe8d5130c82f2ad0483cf3cfb9b0d83e8a061cb301c3c76a772932_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.courier2.blockchain.localhost-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6e3490b505fe8d5130c82f2ad0483cf3cfb9b0d83e8a061cb301c3c76a772932_sk
    ports:
      - 9054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../artifacts/crypto-config/peerOrganizations/courier2.blockchain.localhost/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../artifacts/fabric-ca-server-config-courier2.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml

  peer0.courier2.blockchain.localhost:
    container_name: peer0.courier2.blockchain.localhost
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.courier2.blockchain.localhost
      - CORE_PEER_LOCALMSPID=courier2MSP
      - CORE_PEER_ADDRESS=peer0.courier2.blockchain.localhost:7051
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/courier2.blockchain.localhost/peers/peer0.courier2.blockchain.localhost/:/etc/hyperledger/crypto/peer
    depends_on:
      - ca.courier2.blockchain.localhost
    

  peer1.courier2.blockchain.localhost:
    container_name: peer1.courier2.blockchain.localhost
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.courier2.blockchain.localhost
      - CORE_PEER_LOCALMSPID=courier2MSP
      - CORE_PEER_ADDRESS=peer1.courier2.blockchain.localhost:7051
    ports:
      - 9056:7051
      - 9058:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/courier2.blockchain.localhost/peers/peer1.courier2.blockchain.localhost/:/etc/hyperledger/crypto/peer
    depends_on:
      - ca.courier2.blockchain.localhost
    

  # fabric-rest api server
  api.courier2.blockchain.localhost:
    extends:
      file: base.yaml
      service: api-base
    container_name: api.courier2.blockchain.localhost
    ports:
      - 4002:4000
    environment:
      - ORG=courier2
      - PORT=4000
    volumes:
      - ../artifacts/api/courier2/hosts:/etc/hosts
    depends_on:
      - peer0.courier2.blockchain.localhost
      - peer1.courier2.blockchain.localhost
    

  cli.blockchain.localhost:
    container_name: cli.blockchain.localhost
    extends:
      file: base.yaml
      service: cli-base
    volumes:
      - ../artifacts/crypto-config/ordererOrganizations/blockchain.localhost/orderers/orderer.blockchain.localhost/tls:/etc/hyperledger/crypto/orderer/tls

  cli.courier2.blockchain.localhost:
    container_name: cli.courier2.blockchain.localhost
    extends:
      service: cli.blockchain.localhost
    environment:
      - CORE_PEER_LOCALMSPID=courier2MSP
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/courier2.blockchain.localhost/users/Admin@courier2.blockchain.localhost:/etc/hyperledger/crypto/peer
    

  # simple http server to disseminate certificates
  www.courier2.blockchain.localhost:
    extends:
      file: base.yaml
      service: www-base
    container_name: www.courier2.blockchain.localhost
    ports:
      - 8083:80
